#!/bin/sh
#source ./db.env
echo "Creating database $POSTGRES_DATABASE for $POSTGRES_USER"
psql -c "CREATE USER $POSTGRES_USER WITH LOGIN CREATEDB CREATEROLE REPLICATION PASSWORD '$POSTGRES_PASSWORD';"
psql -U $POSTGRES_USER -c "CREATE DATABASE $POSTGRES_DATABASE WITH OWNER $POSTGRES_USER;"
