
name: NuGet Package (Dev)

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-dev[0-9]*"

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Verify commit exists in origin/develop
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/develop
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Add GitHub package source
      run: dotnet nuget add source https://nuget.pkg.github.com/Crafted-Solutions/index.json -n cs -u ${NUGET_USER} -p ${NUGET_TOKEN} --store-password-in-clear-text
      env:
        NUGET_TOKEN: ${{ secrets.PACKAGE_READ_TOKEN }}
        NUGET_USER: ${{ vars.NUGET_USER }}
    - name: Build
      run: dotnet build -c Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test -c Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack -c Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push "*.nupkg" -s https://nuget.pkg.github.com/Crafted-Solutions/index.json -k ${PACKAGE_TOKEN}
      env:
        PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
    - name: Cleanup
      if: always()
      continue-on-error: true
      run: |
        dotnet nuget remove source cs
